- name: using condition in ansible
  hosts: local
  connection: local
  var_prompt:
   name: my_number
   prompt: Please enter number
   private: false
   tasks:
   - name: print if number is less than 10
     ansible.builtin.debug:
      msg: "given nuber is {{my_number}} is less than 10"
     when:  my_number < 10

   - name: print if number is gater than 10
     ansible.builtin.debug:
      msg: "given nuber is {{my_number}} is gater than 10"
     when:  my_number > 10     

    
      
