 - name: create ec2 and route53 records
   hosts: local
   connection: local
   vars:
     subnet_id: subnet-0f1db1bf16eec673c
     sg_id: "sg-0d528afb2d2d48ee4"
     ami_id: "ami-09c813fb71547fc4f"
     instances:
     - mysql
     - backend
     - frontend
   zone: lakshmangundapu.icu


   tasks:
   - name: create ec2 instance
     amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{  ami_id }}"
     loop: "{{ instances }}"
     register: ec2_instances

   - name: print the ec2 output
     ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

   - name: create r53 instance 
     amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
     loop: "{{ ec2_instance.result }}"
